### ISSUE TITLE
are experimental.custom.tags and attributes coming back?

### ISSUE THREAD

**Issue by bkelley13** [microsoft/vscode-custom-data#1]
I saw the post here of:
https://github.com/microsoft/vscode-custom-data/tree/master/samples/webcomponents
about a month back, and it seems to have re-introduced experimental.custom.tags and attributes again?  I thought it was all now html.customData rather than back to last Nov's custom.tags?

**Comment by octref** [comment]
No, I put together the samples by running `mv` from a few places...I'll update all of them tomorrow.

**Comment by octref** [comment]
Updated webcomponents sample.
