### ISSUE TITLE
Proposal:  package.json support

### ISSUE THREAD

**Issue by bahrus** [microsoft/vscode-custom-data#2]
Extending [this proposal](https://github.com/w3c/webcomponents/issues/776#issuecomment-536749457):

Look for an entry in package.json called "customElements".

If the value is a string, first search for a file relative to the root of the package.

For example:

"customElements": "./custom-elements.json"

Also support searching for a folder:

"customElements": "./custom-elements/"

If it points to a folder,  look for a file within that folder with name most closely aligned with the language preference.  For example, for Algerian Arabic:

"custom-elements/custom-elements.ar-DZ.json"

If no match found, try:

"custom-elements/custom-elements.ar.json"

If that's not found, try:

"custom-elements/custom-elements.json"

If instead of a string, the value of custom elements is an array:

"customElements": ["./src/my-button/my-button.json", "./src/my-input/my-input.json"]

Apply the same rules as above, for each item

All these files would apply to HTML editing, incorporated into /web-data

**Comment by octref** [comment]
The way this support would end up in VS Code is:
- https://github.com/microsoft/vscode/issues/83594 happens
- It becomes possible to write an extension that traverses `node_modules`, looking for packages that contain `custom-elements.json`, transform them into Custom Data format that VS Code can understand, then call the VS Code API to add additional tags for custom elements.

The data format wouldn't need to change for this proposal, so I'm closing.
