### ISSUE TITLE
web-data licensing question

### ISSUE THREAD

**Issue by tomrav** [microsoft/vscode-custom-data#23]
I see that there is a mix of content and licenses in various parts of this repository (depending on their originating source, which makes total sense to me).

I wanted to inquire specifically about the `web-data` package/directory, and the `data` folder within. These don't seem to have a specific license applied, I'm not sure if the license from the root of the project applies, and so I wonder how they are licensed according to you?

Appreciate your help figuring this out.

**Comment by aeschli** [comment]
I added a license file. I hope that's helpful.

**Comment by tomrav** [comment]
That's great, thank you!

**Comment by tomrav** [comment]
Thank you for replying, but I'm still not seeing any license in the `web-data` package folder (or any new commits in the last 5 days).
Something got missed perhaps?

**Comment by aeschli** [comment]
Sorry, now it pushed (https://github.com/microsoft/vscode-custom-data/blob/main/web-data/LICENSE.md) and will be published to npm soon.

**Comment by tomrav** [comment]
Thanks for posting the license. 

I'd like to ask a clarification question.

We're interested in using the two files `browsers.css-data.json` and `browsers.html-data.json`, from the `web-data/data` folder.

How would you say those two files are licensed? I'm not super clear about the distinction between `data` and `content` in the license.  So I'm not sure under which one it falls.

CC BY-SA 2.5 is a viral license (like GPLv3) so this is critical for us to understand before consuming.

Hope this isn't a bother. :)

**Comment by aeschli** [comment]
Sorry, I read up on this and removed the reference to CC BY-SA 2.5. It's now pure MIT.

This is based on my understanding  of the discussion here https://github.com/mdn/data/issues/210#issuecomment-387572808 that we had with MDN.

I'll have this checked with our legal guys, before I'll publish the next version.

You want to have this checked as well, if you have doubts.

**Comment by tomrav** [comment]
Thanks for clearing this up, I'll be sure to run it past our legal too.

**Comment by tomrav** [comment]
Hi, just wondering if it was settled and can be published?
