### ISSUE TITLE
Proposal: Support interplay between JavaScript and HTML

### ISSUE THREAD

**Issue by bahrus** [microsoft/vscode-custom-data#3]
The impact of this support would be much larger should [HTMLModules](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/HTMLModules/explainer.md) ship, and the necessary adjustments for that context be made.

Unlike more design-oriented editors like WebStorm, DreamWeaver (and Visual Studio's deprecated editor), VSCode doesn't seem to exhibit any awareness between the DOM and Script.

For example, suppose you are editing an HTML file:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    
</head>
<body>
    <button id=myButton></button>
    <my-custom-element id=myCustomElement></my-custom-element>
    <script>
        myButton.title = 'hello';
        myCustomElement.addEventListener()
        myCustomElement.myProp=
    </script>
</body>
</html>
```

VSCode doesn't recognize that myButton is an HTMLButtonElement, and myCustomElement is a my-custom-element.  Adding support for this kind of synergy between the two expression types (HTML, JavaScript) would (obviously) make editor support for properties and events meaningful.

Support for an extended schema might also help with JSX and tagged template libraries as well, I assume?

And of course it would quite helpful for the (admittedly minority of) developers who edit HTML files.

**Comment by octref** [comment]
> VSCode doesn't seem to exhibit any awareness between the DOM and Script.

That's right. VS Code's support for HTML and JS are separate, and those support are unaware of DOM.

> VSCode doesn't recognize that myButton is an HTMLButtonElement, and myCustomElement is a my-custom-element. Adding support for this kind of synergy between the two expression types (HTML, JavaScript) 

This is too vague and a lot of work. How can you even be sure `myButton` is `HTMLButtonElement`? And even if VS Code understands there's some sort of connection between, say, `myCustomElement` and `<my-custom-element>`, what then?

I don't think this is feasible. If you are in the scope of something more specific like Vue file, I could implement such support. But for general HTML it's too loose to build any support.

**Comment by bahrus** [comment]
Thanks for considering the request.

At the risk of stating the obvious(ly wong), id's on DOM elements become [global constants](https://2ality.com/2012/08/ids-are-global.html).

I thought it would be easy to parse the HTML, search for the id, and if it is unique, look up the properties/events listed in the (extended) data file corresponding to the tag name, and provide autocomplete while typing JS referring to those global constants.  I'm probably missing something, resulting in our disconnect.

Apologies for my lack of clarity/confusion.

**Comment by octref** [comment]
> At the risk of stating the obvious(ly wong), id's on DOM elements become global constants.

I didn't even know that. Thanks for letting me know.

> I thought it would be easy to parse the HTML, search for the id, and if it is unique, look up the properties/events listed in the (extended) data file corresponding to the tag name, and provide autocomplete while typing JS referring to those global constants.

Parsing HTML and looking for the ID is easy. How to maintain a TS program and constantly add new global variables and update/remove them is hard. I don't think html-languageserver would be interested in doing this...
