### ISSUE TITLE
Proposal:  Add support for extended Schema

### ISSUE THREAD

**Issue by bahrus** [microsoft/vscode-custom-data#4]
Even if VSCode's [lack of support](https://github.com/microsoft/vscode-custom-data/issues/3) for interplay between the HTML DOM and JavaScript means that there might be no pressing need to support events and properties (except for supporting JSX / tagged template literal libraries?), supporting an enhanced schema, as is being discussed [here](https://github.com/webcomponents/custom-elements-json) and being tested out [here](https://github.com/runem/web-component-analyzer), as the default schema, would make editing such JSON files by hand easier.

Admittedly, there might not yet be a consensus on a single schema yet, so maybe this is a bit early.

**Comment by octref** [comment]
As I answered https://github.com/w3c/webcomponents/issues/776#issuecomment-547121704, you need to define "support" before asking for "editor support". `slots` and `events` doesn't entail any editor support that can be easily done. If you just want to see them in auto-completion and hover, you can append those two to the end of the `description` field.
